leftnav:
- identifier: 913f778b-0021-dcad-3496-679d77dd1d96
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 679aac3b-c501-94a6-33b5-d9ac40ad790a
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 08a642c6-918c-6263-cf20-b76dcdfbb963
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: c89be297-2405-dca0-efd8-b374828b3c9c
  name: Case Studies
  pageRef: /pages/case-studies
  weight: 40
- identifier: 854cd7b1-c4d2-05d7-c246-b290c151c27f
  name: Presentations
  pageRef: /pages/presentations
  weight: 50
